server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jasingam.ct4wiau40668.ap-northeast-2.rds.amazonaws.com/jasingam
    username: admin
    password: jasingam
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaehwefehjdslweiuehfb
  thymeleaf:
    cache: false

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  profiles:
    include: API-KEY, AWS-KEY


aws:
  s3:
    bucketName: jasingam-bucket