server:
  port: 8080

spring:
  config:
    import:
      - classpath:config/application-db.properties
      - classpath:config/application-aws.properties
      - classpath:config/application-jwt.properties
      - classpath:config/application-api.properties
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
  jwt:
    secret: ${jwt.secret}
  thymeleaf:
    cache: false

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  openai:
    api:
      key: ${openai.api.key}


aws:
  accessKeyId: ${aws.access.key.id}
  secretKey: ${aws.secret.access.key}
  s3:
    bucketName: ${bucket.name}